Vagrant.configure("2") do |config|
	config.vm.define "nfourS" do |nfourS|
		nfourS.vm.box = "albgarci42/alpine-322"
		nfourS.vm.box_version = "1"

		nfourS.vm.hostname = "nfourS"
		nfourS.vm.network "private_network", ip: "192.168.56.110"
		config.vm.synced_folder ".", "/vagrant", type: "rsync"

		nfourS.vm.provider :libvirt do |libvirt|
			libvirt.memory = 1024
			libvirt.cpus = 1
		end

		nfourS.vm.provision "shell", path: "scripts/install_k3s.sh"
		nfourS.vm.provision "shell", path: "scripts/deploy_app.sh"
	end
end
