Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine319"

	config.vm.provision "shell", inline: <<-SHELL
		apk add --no-cache curl
	SHELL

	config.vm.define "nfourS" do |control|
	  control.vm.hostname = "nfourS"
	  control.vm.network "private_network", ip: "192.168.56.110"
	  control.vm.provider "libvirt" do |libvirt|
		  libvirt.memory = "1024"
		  libvirt.cpus = 1
	  end
	  control.vm.provision "shell", path: "./vagrant/setup.sh", args: ["server"]
	end

    config.vm.define "nfourSW" do |control|
	  control.vm.hostname = "nfourSW"
	  control.vm.network "private_network", ip: "192.168.56.111"
	  control.vm.provider "libvirt" do |libvirt|
		  libvirt.memory = "1024"
		  libvirt.cpus = 1
	  end
	  control.vm.provision "shell", path: "./vagrant/setup.sh", args: ["agent"]
	end

  end




